#
# Makefile for datagram tests for libsocket
# Written by Richard Dawe <richdawe@bigfoot.com>
#

include ../../Makefile.cfg

all:

clean:
	$(MAKE) -C sockvxd clean

distclean:	clean
	$(MAKE) -C sockvxd distclean
	rm -f *.\$$\$$\$$
	rm -f *~