.\" libsocket Copyright 1997, 1998 by Indrek Mandre
.\" libsocket Copyright 1997, 1998 by Richard Dawe
.\" Manual pages written by Richard Dawe
.\"
.TH NETWORKS 5 "17 August 1998" "libsocket 0.7.3" "libsocket Reference"
.SH NAME
networks \- the network name to network IP address mapping file
.SH DESCRIPTION
This file tells the host name resolver the network component of an IP address
corresponding to each network name. This is useful if there is no DNS server
on the network. It can also be used if the DNS server does not have a record
for a particular network name, but its IP address is known.
.sp
The file is a plain ASCII file. Comments are denoted by a hash at the start of
a line. Each line has the following format:
.sp
.RS
.B <IP address> <network name> <alias>
.RE
.sp
e.g.
.RS
# networks - network name to IP address translation file
.br
127       loopback
.br
192.168.0 mynet intranet
.br
.RE
.sp
There should always be a line refering to
.IR loopback .
This is the loopback device, and is always accessible.
.sp
Note 1: Windows doesn't use the aliases, so you will need multiple lines for
the same network IP address to fake aliasing.
.sp
Note 2: The network IP address can be constructed from an IP address and
network mask, e.g. if you have an IP address of 1.2.3.4 and a netmask of
255.255.0.0, then AND'ing them gives a network IP address of 1.2.
.SH FILES
.IR /etc/networks " (Linux),"
.IR C:\eWINDOWS\eNETWORKS " (Windows)"
.SH SEE ALSO
.BR hosts (5)
